version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "deps"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "deps"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
